CREATE TABLE RoleType(
    RoleTypeId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RoleName VARCHAR(20)
);

CREATE TABLE "User"(
    UserId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    SecoundName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Phone VarCHAR(100) UNIQUE NOT NULL
);
CREATE TABLE UserRole(
    RoleId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RoleTypeId INT REFERENCES RoleType(RoleTypeId),
    UserId INT REFERENCES "User"(UserId)
);

CREATE TABLE TokenType(
    TokenTypeId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TokenName VARCHAR(50)
);

CREATE TABLE UserToken(
    TokenId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN TEXT UNIQUE NOT NULL,
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExpireDate TIMESTAMP,
    IsUsed BOOLEAN DEFAULT FALSE,
    UserId INT REFERENCES "User"(UserId),
    TokenTypeId INT REFERENCES TokenType(TokenTypeId)
)
